---
title: "Plot Extended Data Fig. 9 legend"
author: "Marcos Morgan"
output: html_document
---

Load library
```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(knitr)
library(ggplot2)
```

clean stuff
```{r, message=FALSE, warning=FALSE}
rm(list=ls()[!ls() %in% c("table")])
```

Set working directory
```{r setup}
knitr::opts_chunk$set(message = TRUE, warning = TRUE)
opts_knit$set(root.dir = "../")
```

Load helper functions
```{r, message=FALSE, warning=FALSE}
source("scripts/figures_helper_functions.R")
```

Read table
```{r, message=FALSE, warning=FALSE}

if(!(c("table") %in% ls())){
  
  #Loading table
  table <- read.csv("views/table/TAIL-seq_Morganetal2017.csv", stringsAsFactors=FALSE)
  table <- table %>% rename(palen = poly_a_tail_length, cell = cell_tissue, mod = modification, short = short_tail, 
                            type = modification_type, type_short = modification_type_short, gv = gv_upregulated) %>% 
                     rowwise() %>% mutate(cell      = rename_cell(cell)) %>%
                     rowwise() %>% mutate(treatment = rename_treatment(cell, treatment)) %>% ungroup()
  
} 

head(table)
```

Generate legends
```{r, message=FALSE, warning=FALSE}

generate_legend <- function(reader, type_short_p){

    reader           <- reader %>% mutate(cell = factor(cell, levels = c("gv", "liver", "bm", "mefs", "escs")))

    transcripts     <- reader %>% select(cell, treatment,type_short)   %>% 
                             group_by(cell, treatment,type_short) %>% mutate(trans = n())      %>% ungroup() %>%
                             group_by(cell, treatment)            %>% mutate(trans_all = n())  %>% ungroup() %>%
                             unique()

    genes          <- reader %>% select(cell, treatment,type_short, gene) %>% unique() %>% select(cell, treatment,type_short) %>%
                             group_by(cell, treatment,type_short)    %>% mutate(gen     = n()) %>% ungroup() %>%
                             group_by(cell, treatment)               %>% mutate(gen_all = n()) %>% ungroup() %>%
                             unique()

    legend1         <- full_join(transcripts, genes)

    legend1         <- full_join(transcripts, genes) %>% filter(type_short == type_short_p) 

    legend1         <- legend1 %>% select(-trans_all, -gen_all, -type_short) %>% arrange(cell) %>%
                             mutate(print = paste(as.character(trans), " ", "(",  as.character(gen), ")", sep="")) %>%
                             select(-cell, -trans, -gen)  

    show(legend1)
    
    print   <- factor(legend1$print, levels = legend1$print)
    legend1 <- as.data.frame(print) %>% mutate(rep = 0)
    plot    <- ggplot(legend1, aes(x=print)) + theme(axis.text.x = element_text(angle = 90, hjust = 1))
    
    
    
    return(plot)
}

```

Save Extended Data Fig. 9a legend
```{r, message=FALSE, warning=FALSE}
reads           <- table 
plot <- generate_legend(reads, "C")
plot
ggsave("plots/final_figures/ED_figure_9_a_a_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)

reads           <- table %>% filter(short == "yes") 
plot <- generate_legend(reads, "C")
plot
ggsave("plots/final_figures/ED_figure_9_a_b_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)

reads           <- table %>% filter(short == "no") 
plot <- generate_legend(reads, "C")
plot
ggsave("plots/final_figures/ED_figure_9_a_c_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)
```

Save Extended Data Fig. 9b legend
```{r, message=FALSE, warning=FALSE}
reads           <- table 
plot <- generate_legend(reads, "G")
plot
ggsave("plots/final_figures/ED_figure_9_b_a_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)

reads           <- table %>% filter(short == "yes") 
plot <- generate_legend(reads, "G")
plot
ggsave("plots/final_figures/ED_figure_9_b_b_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)

reads           <- table %>% filter(short == "no") 
plot <- generate_legend(reads, "G")
plot
ggsave("plots/final_figures/ED_figure_9_b_c_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)
```

```{r}

```


