---
title: "Source data Extended Data Fig. 7b and 7c. Legends Extended Data Fig. 7b and 7c"
author: "Marcos Morgan"
output: html_document
---

Load library
```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(knitr)
library(ggplot2)
```

Clean the environment
```{r, message=FALSE, warning=FALSE}
rm(list=ls()[!ls() %in% c("table")])
```

Set working directory
```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
opts_knit$set(root.dir = "../")
```

Load helper functions
```{r, message=FALSE, warning=FALSE}
source("scripts/figures_helper_functions.R")
```

Read table
```{r, message=FALSE, warning=FALSE}

if(!(c("table") %in% ls())){
  
  #Loading table
  table <- read.csv("views/table/TAIL-seq_Morganetal2017.csv", stringsAsFactors=FALSE)
  table <- table %>% rename(palen = poly_a_tail_length, cell = cell_tissue, mod = modification, short = short_tail, 
                            type = modification_type, type_short = modification_type_short, gv = gv_upregulated) %>% 
                     rowwise() %>% mutate(cell      = rename_cell(cell)) %>%
                     rowwise() %>% mutate(treatment = rename_treatment(cell, treatment)) %>% ungroup()
  
} 

head(table)
```

View of frequency changes
```{r, message=FALSE, warning=FALSE}
reads_stats   <- table %>% group_by(cell, treatment, sample, short)      %>% mutate(all= n())  %>% ungroup() %>%
                    group_by(cell, treatment, sample, short, type) %>% mutate(mod_count = n()) %>% ungroup() %>%
                    rowwise() %>% mutate(frequency = 100*mod_count/all)                                      %>%
                    select(cell, treatment, sample, short, type, frequency) %>% unique()           

reads_stats   <- missing_oligo(reads_stats)
                                             
reads_stats   <-    reads_stats %>% group_by(cell, treatment, short, type) %>%
                    mutate(mean = mean(frequency), sd = sd(frequency), frequencies=list(frequency)) %>% ungroup()

show(reads_stats)
```

Calculate t-test
```{r, message=FALSE, warning=FALSE}
reads_stats_t   <- reads_stats %>% select(cell, treatment, short, type, frequencies) %>% unique() %>% spread(treatment, frequencies)
reads_stats_t   <- reads_stats_t %>% rowwise() %>% 
                                     mutate( pval = ifelse(length(dcko) > 1  & length(ctrl) > 1, 
                                                             t.test(dcko, ctrl, var.equal=TRUE)$p.value, NA)) %>%
                                     mutate( star = ifelse(!is.na(pval), sig(pval),NA)) %>%
                                     select(cell, short, type, pval, star)

reads_stats   <- full_join(reads_stats, reads_stats_t) %>% select(-frequencies)
show(reads_stats)
```

Calculate fold change
```{r, message=FALSE, warning=FALSE}
reads_stats_f   <- reads_stats %>% select(cell, treatment, short, type, mean) %>% unique() %>% spread(treatment, mean)
reads_stats_f   <- reads_stats_f %>% rowwise() %>% 
                                     mutate(change = ifelse(!is.na(ctrl)  & !is.na(dcko), 
                                                            ifelse((ctrl/dcko) > 1, ctrl/dcko, -dcko/ctrl), NA)) %>%
                                     select(cell, short, type, change)

reads_stats    <- left_join(reads_stats, reads_stats_f, by = c("cell", "short", "type"))
reads_stats_   <- subset(reads_stats, !is.na(reads_stats$change))
show(reads_stats)
```

Creating the same table without making differences between short and long tails
```{r, message=FALSE, warning=FALSE}
reads_stats   <- table %>% group_by(cell, treatment, sample) %>% mutate(all       = n()) %>% ungroup() %>%
                    group_by(cell, treatment, sample, type)  %>% mutate(mod_count = n()) %>% ungroup() %>%
                    rowwise() %>% mutate(frequency = 100*mod_count/all)                                %>%
                    select(cell, treatment, sample, type, frequency) %>% unique()           

reads_stats   <- missing_oligo(reads_stats)
                                             
reads_stats   <-    reads_stats %>% group_by(cell, treatment, type) %>%
                    mutate(mean = mean(frequency), sd = sd(frequency), frequencies=list(frequency)) %>% ungroup()


show(reads_stats)

reads_stats_t   <- reads_stats %>% select(cell, treatment, type, frequencies) %>% unique() %>% spread(treatment, frequencies)
reads_stats_t   <- reads_stats_t %>% rowwise() %>% 
                                     mutate( pval = ifelse(length(dcko) > 1  & length(ctrl) > 1, 
                                                             t.test(dcko, ctrl, var.equal=TRUE)$p.value, NA)) %>%
                                     mutate( star = ifelse(!is.na(pval), sig(pval),NA)) %>%
                                     select(cell, type, pval, star)

reads_stats     <- full_join(reads_stats, reads_stats_t) %>% select(-frequencies)
show(reads_stats)

reads_stats_f   <- reads_stats %>% select(cell, treatment, type, mean) %>% unique() %>% spread(treatment, mean)
reads_stats_f   <- reads_stats_f %>% rowwise() %>% 
                                     mutate(change = ifelse(!is.na(ctrl)  & !is.na(dcko), 
                                                            ifelse((ctrl/dcko) > 1, ctrl/dcko, -dcko/ctrl), NA)) %>%
                                     select(cell, type, change)

reads_stats     <- left_join(reads_stats, reads_stats_f, by = c("cell", "type")) %>% rowwise() %>% mutate(short = "all")
reads_stats     <- subset(reads_stats, !is.na(reads_stats$change))

reads_stats_ <- bind_rows(reads_stats_, reads_stats)

show(reads_stats)
```

```{r, message=FALSE, warning=FALSE}
reads_stats_ <- reads_stats_ %>% rowwise() %>% mutate(label   = paste(as.character(signif(change, digits = 2)), "X" , "\n", star, sep =""),
                                                      mean_sd = mean + sd)
```

Saving source data
```{r, message=FALSE, warning=FALSE}
write.csv(reads_stats_ %>% filter(type == "monoT"),  "views/final_figures/ED_figure_7_b.csv")
write.csv(reads_stats_ %>% filter(type == "oligoT"), "views/final_figures/ED_figure_7_c.csv")
```

Generate figure legends
```{r, message=FALSE, warning=FALSE}

generate_legend <- function(reader, type_){

    reader           <- reader %>% mutate(cell = factor(cell, levels = c("gv","liver", "bm", "mefs", "escs")))

    transcripts     <- reader %>% select(cell, treatment, type)   %>% 
                             group_by(cell, treatment,type) %>% mutate(trans = n())      %>% ungroup() %>%
                             group_by(cell, treatment)            %>% mutate(trans_all = n())  %>% ungroup() %>%
                             unique()

    genes          <- reader %>% select(cell, treatment, type, gene) %>% unique() %>% select(cell, treatment,type) %>%
                             group_by(cell, treatment,type)    %>% mutate(gen     = n()) %>% ungroup() %>%
                             group_by(cell, treatment)         %>% mutate(gen_all = n()) %>% ungroup() %>%
                             unique()

    legend1         <- full_join(transcripts, genes)

    legend1         <- full_join(transcripts, genes) %>% filter(type == type_) 

    legend1         <- legend1 %>% select(-trans_all, -gen_all, -type) %>% arrange(cell) %>%
                             mutate(print = paste(as.character(trans), "\n", "(",  as.character(gen), ")", sep="")) %>%
                             select(-cell, -trans, -gen)  

    show(legend1)
    
    print   <- factor(legend1$print, levels = legend1$print)
    legend1 <- as.data.frame(print) %>% mutate(rep = 0)
    plot    <- ggplot(legend1, aes(x=print)) + theme(axis.text.x = element_text(angle = 90, hjust = 1))
    
    
    
    return(plot)
}

```

Save legends 
```{r, message=FALSE, warning=FALSE}
reads           <- table 
plot <- generate_legend(reads, "monoT")
plot
ggsave("plots/final_figures/ED_figure_7_b_a_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)

reads           <- table %>% filter(short == "yes") 
plot <- generate_legend(reads, "monoT")
plot
ggsave("plots/final_figures/ED_figure_7_b_b_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)

reads           <- table %>% filter(short == "no") 
plot <- generate_legend(reads, "monoT")
plot
ggsave("plots/final_figures/ED_figure_7_b_c_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)
```

```{r, message=FALSE, warning=FALSE}
reads           <- table 
plot <- generate_legend(reads, "oligoT")
plot
ggsave("plots/final_figures/ED_figure_7_c_a_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)

reads           <- table %>% filter(short == "yes") 
plot <- generate_legend(reads, "oligoT")
plot
ggsave("plots/final_figures/ED_figure_7_c_b_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)

reads           <- table %>% filter(short == "no") 
plot <- generate_legend(reads, "oligoT")
plot
ggsave("plots/final_figures/ED_figure_7_c_c_panel.pdf", plot, width=55, height=20, units = "mm", useDingbats=FALSE)
```

```{r}

```


